# Standard upstream distribution feeds
src-git packages https://openwrt.org
src-git luci https://openwrt.org

# Inversion link: forces OpenWrt to read your local folder as an external package source
src-link custom_project ../my-custom-packages
